title: "Charlie Conroy"
subtitle: "Professor of Astronomy"
description: "Academic website for Charlie Conroy, Professor of Astronomy at Harvard University"
baseurl: ""
url: "https://yourusername.github.io"

author:
  name: "Charlie Conroy"
  title: "Professor of Astronomy"
  institution: "Harvard University"
  email: "cconroy@cfa.harvard.edu"

# Remove the theme to use custom styling
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - research.md
  - publications.md
  - contact.md

# Social links (optional)
github_username: yourusername
twitter_username: yourusername

# Build settings
markdown: kramdown
highlighter: rouge
