title: "Charlie Conroy"
subtitle: "Professor of Astronomy"
description: "Academic website for Charlie Conroy, Professor of Astronomy at Harvard University"
baseurl: ""
url: "https://yourusername.github.io"

# Author information
author:
  name: "Charlie Conroy"
  title: "Professor of Astronomy"
  institution: "Harvard University"
  email: "cconroy@cfa.harvard.edu"
  orcid: "0000-0000-0000-0000"
  twitter: "username"
  github: "username"
  google_scholar: "scholar_id"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:name/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# SEO
lang: en_US
timezone: America/New_York

# Navigation
navigation:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
  - name: "Research"
    url: "/research/"
  - name: "Publications"
    url: "/publications/"
  - name: "Teaching"
    url: "/teaching/"
  - name: "Blog"
    url: "/blog/"
  - name: "CV"
    url: "/cv/"
  - name: "Contact"
    url: "/contact/"

# Footer links
footer_links:
  - name: "ORCID"
    url: "https://orcid.org/0000-0000-0000-0000"
    icon: "fab fa-orcid"
  - name: "Google Scholar"
    url: "https://scholar.google.com/citations?user=SCHOLAR_ID"
    icon: "fas fa-graduation-cap"
  - name: "GitHub"
    url: "https://github.com/username"
    icon: "fab fa-github"
  - name: "Twitter"
    url: "https://twitter.com/username"
    icon: "fab fa-twitter"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/